[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fusion_swap = "5uzpYuGqBaetRMXPDtGWGN9W4mdmgBzpGHcQACrZ1npi"
whitelist = "DyXFcRxGWFoMz1j76SeMXHjQqZKudLXeJY3h1K7BNJiQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
