[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fusion_swap = "12nFacVKzTjC5d82ZVV3Le9PFrnFw2vw2LR751MkXZFy"
whitelist = "9HAr4VXm3PEmhMu2R2FCVoJ87VFCB48xRk3o6RZHRVjf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
